version: '3.6'
services:
  ui:
    build:
      context: .
      dockerfile: UIDockerfile
    container_name: ui
    ports:
      - '4600:443'
    networks:
      - samplenet
    links:
      - 'api:api'
  api:
    build:
      context: .
      dockerfile: AppDockerfile
    container_name: api
    ports:
      - '5550:5550'
    depends_on:
      - db
    networks:
      - samplenet
    links:
      - 'db:db'
  db: 
    build:
      context: .
      dockerfile: DBDockerfile
    container_name: db
    volumes:
      - postgresdb:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fastcode
      POSTGRES_DB: codegenoffline
    ports:
      - '5433:5432'
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -U postgres'
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - samplenet
networks:
  samplenet: null
volumes:
  postgresdb: {}
